#! /bin/sh

mode="664"

if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

case "$1" in
    start)
        echo ">> Starting scull kernel module..."
        /etc/init.d/scull_load
        echo ">> Starting faulty kernel module..."
        /etc/init.d/module_load faulty
        echo ">> Starting hello kernel module..."
        /etc/init.d/module_load hello use-modprobe
        ;;
    stop)
        # start-stop-daemon -K -n aesdsocket
        echo "<< Stoping scull kernel module..."
        /etc/init.d/scull_unload
        for module in faulty hello; do
            echo "<< Stoping ${module} kernel module..."
            /etc/init.d/module_unload $module
        done
        ;;
    *)
        echo "Usage: $0 {sart|stop}"
        exit 1
esac

exit 0
